num = int(input("Insira um numero com 5 digitos: "))
n = str(num)
print("Milhar: {}".format(n[0]))
print("Centena: {}".format(n[1]))
print("Dezena: {}".format(n[2]))
print("Unidade: {}".format(n[3]))
